import os
SKIP_PREFILL = bool(int(os.getenv('SKIP_PREFILL', 0)))
SKIP_DECODE = bool(int(os.getenv('SKIP_DECODE', 0)))
GPU_FREQ = int(os.getenv('GPU_FREQ', '1830'))

OVERWRITE_PREFILL_LEN = os.getenv('OVERWRITE_PREFILL_LEN')
if OVERWRITE_PREFILL_LEN:
    OVERWRITE_PREFILL_LEN = int(OVERWRITE_PREFILL_LEN)

OVERWRITE_DECODE_LEN = os.getenv('OVERWRITE_DECODE_LEN')
if OVERWRITE_DECODE_LEN:
    OVERWRITE_DECODE_LEN = int(OVERWRITE_DECODE_LEN)

PRINT_EXCEPT_MSG = bool(int(os.getenv('PRINT_EXCEPT_MSG', '0')))

SCALE_ARRIVAL_TIME = bool(int(os.getenv('SCALE_ARRIVAL_TIME', '0')))

OPTIMIZE_ENERGY = bool(int(os.getenv('OPTIMIZE_POWER', '0')))

IGNORE_FIRST_AND_LAST_QUARTER = bool(int(os.getenv('IGNORE_FIRST_AND_LAST_QUARTER', '0')))