import os
SKIP_PREFILL = bool(int(os.getenv('SKIP_PREFILL', 0)))
SKIP_DECODE = bool(int(os.getenv('SKIP_DECODE', 0)))
GPU_FREQ = int(os.getenv('GPU_FREQ', '1410'))

OVERWRITE_PREFILL_LEN = os.getenv('OVERWRITE_PREFILL_LEN')
if OVERWRITE_PREFILL_LEN:
    OVERWRITE_PREFILL_LEN = int(OVERWRITE_PREFILL_LEN)

OVERWRITE_DECODE_LEN = os.getenv('OVERWRITE_DECODE_LEN')
if OVERWRITE_DECODE_LEN:
    OVERWRITE_DECODE_LEN = int(OVERWRITE_DECODE_LEN)

PRINT_EXCEPT_MSG = bool(int(os.getenv('PRINT_EXCEPT_MSG', '0')))
